name: logcat-colorize
version: "0.8.0"
summary: logcat-colorize
confinement: strict
grade: stable
description: |
  logcat-colorize is a software that parses Android logcat output and
  prints it to stdout with improved formatting. Colors are added to the
  output to make it more clear. You'll still be able to add filters using
  the adb command.

apps:
  logcat-colorize:
    command: usr/bin/logcat-colorize
  logcat:
    command: usr/bin/logcat

parts:
  logcat-colorize:
    plugin: make
    source-type: local
    source: ..
    build-packages:
      - g++
      - make
      - libboost-regex-dev
      - libboost-program-options-dev
    stage-packages:
      - libboost-regex1.58.0
      - libboost-program-options1.58.0
  logcat:
    plugin: dump
    source: ../
    source-type: local
